spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger-service
    username: tony
    password: ledgerpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # this is because Flyway will handle migrations
    show-sql: true
    open-in-view: false

  flyway:
    url: jdbc:postgresql://localhost:5432/ledger-service
    user: migration-admin
    password: migration